import { Plant } from "@/types/plant";

export const DEMO_PLANTS: Plant[] = [
  {
    id: "1",
    slug: "monstera-deliciosa",
    name: "Monstera",
    latin_name: "Monstera deliciosa",
    family: "Aracées",
    description:
      "Le Monstera deliciosa, aussi appelé « plante gruyère » pour ses feuilles perforées caractéristiques, est l'une des plantes d'intérieur les plus populaires. Originaire des forêts tropicales d'Amérique centrale, il peut atteindre plusieurs mètres de haut en conditions idéales.",
    care_level: "facile",
    watering: "modéré",
    watering_notes: "Arroser quand les 2-3 premiers centimètres de terre sont secs. Réduire en hiver.",
    light: "lumière indirecte",
    humidity: 60,
    temperature_min: 15,
    temperature_max: 30,
    soil: "Terreau universel bien drainant, mélangé à de la perlite",
    fertilizer: "Engrais liquide toutes les 2 semaines de mars à septembre",
    repotting: "Tous les 2 ans au printemps dans un pot légèrement plus grand",
    origin: "Amérique centrale (Mexique, Panama)",
    height_min: 50,
    height_max: 300,
    toxicity: "toxique",
    toxicity_details: "Toxique pour les chats et les chiens. Irritant pour la peau.",
    images: [],
    thumbnail: "",
    tags: ["tropical", "intérieur", "grandes feuilles", "dépolluante"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    slug: "pothos",
    name: "Pothos",
    latin_name: "Epipremnum aureum",
    family: "Aracées",
    description:
      "Le Pothos est une plante grimpante ou retombante très résistante, idéale pour les débutants.",
    care_level: "facile",
    watering: "modéré",
    watering_notes: "Arroser quand la terre est sèche sur 2-3 cm.",
    light: "mi-ombre",
    humidity: 50,
    temperature_min: 10,
    temperature_max: 30,
    soil: "Terreau universel",
    fertilizer: "Engrais liquide une fois par mois en période de croissance",
    repotting: "Tous les 2-3 ans",
    origin: "Polynésie",
    height_min: 30,
    height_max: 200,
    toxicity: "toxique",
    toxicity_details: "Toxique pour les animaux domestiques si ingéré.",
    images: [],
    thumbnail: "",
    tags: ["retombant", "intérieur", "débutant", "dépolluante"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    slug: "ficus-lyrata",
    name: "Ficus Lyrata",
    latin_name: "Ficus lyrata",
    family: "Moracées",
    description: "Le Ficus lyrata est une plante tendance aux grandes feuilles ondulées.",
    care_level: "intermédiaire",
    watering: "modéré",
    watering_notes: "Arroser quand le premier centimètre de terre est sec.",
    light: "lumière indirecte",
    humidity: 55,
    temperature_min: 16,
    temperature_max: 28,
    soil: "Terreau bien drainant avec perlite",
    fertilizer: "Engrais équilibré toutes les 2 semaines au printemps et en été",
    repotting: "Tous les 2 ans quand les racines sortent du pot",
    origin: "Afrique de l'Ouest",
    height_min: 50,
    height_max: 250,
    toxicity: "légèrement toxique",
    toxicity_details: "La sève peut irriter la peau.",
    images: [],
    thumbnail: "",
    tags: ["tropical", "tendance", "grandes feuilles", "intérieur"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    slug: "aloe-vera",
    name: "Aloe Vera",
    latin_name: "Aloe barbadensis miller",
    family: "Asphodelacées",
    description: "L'Aloe vera est une plante succulente aux feuilles charnues remplies d'un gel aux multiples vertus.",
    care_level: "facile",
    watering: "rare",
    watering_notes: "Arroser abondamment puis attendre que la terre soit complètement sèche.",
    light: "plein soleil",
    humidity: 30,
    temperature_min: 10,
    temperature_max: 35,
    soil: "Terreau pour cactées et succulentes, très drainant",
    fertilizer: "Engrais pour cactées une fois par mois en été",
    repotting: "Tous les 2-3 ans",
    origin: "Afrique du Nord, Péninsule arabique",
    height_min: 20,
    height_max: 80,
    toxicity: "légèrement toxique",
    toxicity_details: "Le gel est bénéfique pour l'humain mais toxique pour les chats et les chiens.",
    images: [],
    thumbnail: "",
    tags: ["succulente", "médicinale", "soleil", "débutant"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
