import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const PLANTS = [
  { slug: "calathea-orbifolia", name: "Calathea Orbifolia", latin_name: "Calathea orbifolia", family: "Marantacées", description: "La Calathea orbifolia est une plante tropicale aux grandes feuilles rondes striées de bandes argentées et vertes. Elle est très appréciée pour son feuillage décoratif spectaculaire.", care_level: "intermédiaire", watering: "régulier", watering_notes: "Arroser régulièrement avec de l'eau non calcaire. Garder le substrat légèrement humide.", light: "lumière indirecte", humidity: 70, temperature_min: 16, temperature_max: 27, soil: "Terreau universel mélangé à de la tourbe", fertilizer: "Engrais liquide toutes les 2 semaines au printemps et en été", repotting: "Tous les 2 ans au printemps", origin: "Bolivie", height_min: 30, height_max: 60, toxicity: "non toxique", toxicity_details: "Non toxique pour les humains et les animaux.", tags: ["tropical", "feuillage décoratif", "intérieur", "ombre"] },
  { slug: "sansevieria", name: "Sansevière", latin_name: "Sansevieria trifasciata", family: "Asparagacées", description: "La Sansevière, aussi appelée langue de belle-mère, est une plante succulente extrêmement robuste. Ses feuilles dressées vert foncé bordées de jaune en font une plante très décorative et presque indestructible.", care_level: "facile", watering: "rare", watering_notes: "Arroser très peu, laisser la terre sécher complètement entre deux arrosages. Très résistante à la sécheresse.", light: "mi-ombre", humidity: 30, temperature_min: 10, temperature_max: 35, soil: "Terreau pour cactées et succulentes", fertilizer: "Engrais pour plantes vertes une fois par mois en été", repotting: "Tous les 3-4 ans", origin: "Afrique de l'Ouest tropicale", height_min: 30, height_max: 120, toxicity: "toxique", toxicity_details: "Toxique pour les chats et les chiens si ingéré.", tags: ["succulente", "dépolluante", "débutant", "intérieur"] },
  { slug: "spathiphyllum", name: "Spathiphyllum", latin_name: "Spathiphyllum wallisii", family: "Aracées", description: "Le Spathiphyllum, ou fleur de lune, est une plante d'intérieur très appréciée pour ses élégantes fleurs blanches et son feuillage vert lustré. C'est l'une des meilleures plantes dépolluantes.", care_level: "facile", watering: "modéré", watering_notes: "Arroser régulièrement en maintenant le sol légèrement humide. Sensible au calcaire.", light: "ombre", humidity: 60, temperature_min: 15, temperature_max: 30, soil: "Terreau universel riche et drainant", fertilizer: "Engrais liquide toutes les 3 semaines de mars à septembre", repotting: "Tous les 2 ans", origin: "Amérique centrale et tropicale", height_min: 30, height_max: 90, toxicity: "toxique", toxicity_details: "Toxique pour les animaux domestiques, irritant pour la peau.", tags: ["fleurs blanches", "dépolluante", "ombre", "intérieur"] },
  { slug: "zamioculcas", name: "ZZ Plant", latin_name: "Zamioculcas zamiifolia", family: "Aracées", description: "Le ZZ Plant est une plante tropicale africaine aux feuilles ovales vert foncé très brillantes. Extrêmement résistante, elle supporte la sécheresse, le manque de lumière et l'oubli d'arrosage.", care_level: "facile", watering: "rare", watering_notes: "Arroser tous les 15-20 jours en été, une fois par mois en hiver. Supporte très bien la sécheresse.", light: "mi-ombre", humidity: 40, temperature_min: 15, temperature_max: 30, soil: "Terreau universel drainant avec perlite", fertilizer: "Engrais liquide une fois par mois au printemps et en été", repotting: "Tous les 2-3 ans", origin: "Afrique de l'Est (Kenya, Tanzanie)", height_min: 40, height_max: 100, toxicity: "toxique", toxicity_details: "Toutes les parties sont toxiques. Irritant pour la peau et les yeux.", tags: ["résistante", "débutant", "intérieur", "ombre"] },
  { slug: "ficus-benjamina", name: "Ficus Benjamina", latin_name: "Ficus benjamina", family: "Moracées", description: "Le Ficus benjamina, ou figuier pleureur, est un arbre d'intérieur aux petites feuilles ovales brillantes disposées sur des rameaux retombants. Il peut devenir très grand avec le temps.", care_level: "intermédiaire", watering: "modéré", watering_notes: "Arroser modérément, laisser sécher la surface entre deux arrosages. Sensible aux courants d'air.", light: "lumière indirecte", humidity: 50, temperature_min: 16, temperature_max: 30, soil: "Terreau universel bien drainant", fertilizer: "Engrais liquide toutes les 2 semaines de mars à octobre", repotting: "Tous les 2 ans", origin: "Asie du Sud-Est, Australie", height_min: 50, height_max: 300, toxicity: "légèrement toxique", toxicity_details: "La sève peut provoquer des irritations cutanées. Légèrement toxique pour les animaux.", tags: ["arbre", "intérieur", "feuillage vert"] },
  { slug: "dracaena-marginata", name: "Dracaena", latin_name: "Dracaena marginata", family: "Asparagacées", description: "Le Dracaena marginata, avec ses longues feuilles étroites bordées de rouge ou de rose, est une plante d'intérieur élégante et facile à entretenir. Très dépolluante.", care_level: "facile", watering: "modéré", watering_notes: "Laisser sécher les 2-3 premiers cm entre les arrosages. Sensible au fluor, utiliser de l'eau filtrée.", light: "lumière indirecte", humidity: 40, temperature_min: 15, temperature_max: 30, soil: "Terreau universel légèrement acide", fertilizer: "Engrais liquide une fois par mois au printemps et en été", repotting: "Tous les 2-3 ans", origin: "Madagascar", height_min: 50, height_max: 250, toxicity: "toxique", toxicity_details: "Toxique pour les chats et les chiens.", tags: ["dépolluante", "tropical", "intérieur", "facile"] },
  { slug: "begonia-rex", name: "Bégonia Rex", latin_name: "Begonia rex", family: "Bégoniacées", description: "Le Bégonia Rex est une plante spectaculaire aux feuilles asymétriques aux couleurs et motifs variés : rouge, argent, vert, violet. C'est l'une des plantes d'intérieur les plus décoratives.", care_level: "intermédiaire", watering: "modéré", watering_notes: "Arroser par le bas pour éviter de mouiller les feuilles. Laisser sécher légèrement entre les arrosages.", light: "lumière indirecte", humidity: 60, temperature_min: 16, temperature_max: 26, soil: "Terreau léger et bien drainant", fertilizer: "Engrais liquide toutes les 2 semaines en période de croissance", repotting: "Tous les ans au printemps", origin: "Inde, Asie du Sud-Est", height_min: 20, height_max: 45, toxicity: "toxique", toxicity_details: "Toxique pour les animaux si ingéré. Irritant pour la peau.", tags: ["feuillage coloré", "intérieur", "décoratif"] },
  { slug: "orchidee-phalaenopsis", name: "Orchidée Phalaenopsis", latin_name: "Phalaenopsis amabilis", family: "Orchidacées", description: "L'orchidée Phalaenopsis, ou orchidée papillon, est la plus cultivée au monde. Ses fleurs élégantes durent plusieurs mois et se déclinent en blanc, rose, violet et jaune.", care_level: "intermédiaire", watering: "modéré", watering_notes: "Arroser une fois par semaine en trempant le pot 10 minutes puis en le laissant bien égoutter.", light: "lumière indirecte", humidity: 55, temperature_min: 18, temperature_max: 28, soil: "Substrat spécial orchidées (écorces de pin)", fertilizer: "Engrais spécial orchidées toutes les 2 semaines en période de croissance", repotting: "Tous les 2 ans après la floraison", origin: "Asie du Sud-Est, Australie", height_min: 30, height_max: 70, toxicity: "non toxique", toxicity_details: "Non toxique pour les humains et les animaux.", tags: ["fleurs", "intérieur", "décoratif", "longue floraison"] },
  { slug: "cactus-cereus", name: "Cactus Cereus", latin_name: "Cereus repandus", family: "Cactacées", description: "Le Cereus est un grand cactus colonnaire aux nervures prononcées. Très facile à cultiver, il peut atteindre plusieurs mètres de haut et fleurit la nuit de grandes fleurs blanches.", care_level: "facile", watering: "rare", watering_notes: "Arroser très peu, une fois tous les 15-30 jours en été, presque pas en hiver.", light: "plein soleil", humidity: 20, temperature_min: 5, temperature_max: 40, soil: "Terreau pour cactées, très drainant", fertilizer: "Engrais pour cactées une fois en début de saison", repotting: "Tous les 3-4 ans", origin: "Amérique du Sud (Brésil, Argentine)", height_min: 30, height_max: 600, toxicity: "non toxique", toxicity_details: "Non toxique mais les épines peuvent blesser.", tags: ["cactus", "soleil", "débutant", "intérieur/extérieur"] },
  { slug: "hoya-carnosa", name: "Hoya", latin_name: "Hoya carnosa", family: "Apocynacées", description: "Le Hoya carnosa est une plante grimpante aux feuilles épaisses et charnues, qui produit de magnifiques fleurs en forme d'étoile dégageant un parfum sucré. Très résistant.", care_level: "facile", watering: "modéré", watering_notes: "Laisser sécher le substrat entre deux arrosages. Ne pas trop arroser pour éviter la pourriture.", light: "lumière indirecte", humidity: 50, temperature_min: 15, temperature_max: 30, soil: "Mélange terreau universel et perlite", fertilizer: "Engrais liquide une fois par mois de mars à septembre", repotting: "Tous les 2-3 ans", origin: "Asie de l'Est et du Sud-Est", height_min: 50, height_max: 400, toxicity: "non toxique", toxicity_details: "Non toxique pour les humains et les animaux.", tags: ["grimpante", "fleurs parfumées", "intérieur", "facile"] },
  { slug: "lavande", name: "Lavande", latin_name: "Lavandula angustifolia", family: "Lamiacées", description: "La lavande est une plante aromatique méditerranéenne aux tiges fleuries d'un magnifique violet-bleu dégageant un parfum caractéristique et apaisant. Idéale en pot ou au jardin.", care_level: "facile", watering: "rare", watering_notes: "Arroser peu, la lavande craint l'excès d'eau. Une fois par semaine en été, moins en hiver.", light: "plein soleil", humidity: 25, temperature_min: -10, temperature_max: 35, soil: "Terreau drainant, calcaire si possible", fertilizer: "Peu de fertilisation, légèrement en début de printemps", repotting: "Tous les 2-3 ans ou quand elle dépasse son pot", origin: "Méditerranée, Europe du Sud", height_min: 30, height_max: 80, toxicity: "non toxique", toxicity_details: "Non toxique. Utilisée en phytothérapie.", tags: ["aromatique", "extérieur", "méditerranéenne", "résistante"] },
  { slug: "rosier-miniature", name: "Rosier Miniature", latin_name: "Rosa chinensis minima", family: "Rosacées", description: "Le rosier miniature est une version réduite du rosier traditionnel, idéale pour une culture en pot. Il produit de nombreuses petites fleurs colorées tout au long de la belle saison.", care_level: "intermédiaire", watering: "régulier", watering_notes: "Arroser régulièrement en évitant de mouiller les feuilles. Laisser sécher légèrement entre deux arrosages.", light: "plein soleil", humidity: 50, temperature_min: -5, temperature_max: 30, soil: "Terreau pour rosiers, riche et bien drainant", fertilizer: "Engrais pour rosiers toutes les 2 semaines de mars à septembre", repotting: "Tous les 2 ans au printemps", origin: "Chine", height_min: 20, height_max: 50, toxicity: "non toxique", toxicity_details: "Non toxique mais les épines peuvent blesser.", tags: ["fleurs", "extérieur/intérieur", "coloré", "parfumé"] },
  { slug: "fougere-nephrolepis", name: "Fougère de Boston", latin_name: "Nephrolepis exaltata", family: "Lomariopsidacées", description: "La fougère de Boston est une fougère retombante aux frondes arquées d'un beau vert vif. Elle aime l'humidité et purifie efficacement l'air intérieur.", care_level: "intermédiaire", watering: "régulier", watering_notes: "Garder le substrat constamment humide sans excès. Brumiser les feuilles régulièrement.", light: "lumière indirecte", humidity: 70, temperature_min: 15, temperature_max: 26, soil: "Terreau universel riche et retenant l'humidité", fertilizer: "Engrais liquide toutes les 2 semaines au printemps et en été", repotting: "Tous les 2 ans au printemps", origin: "Amérique tropicale, Afrique", height_min: 30, height_max: 90, toxicity: "non toxique", toxicity_details: "Non toxique pour les humains et les animaux.", tags: ["retombante", "dépolluante", "humidité", "intérieur"] },
  { slug: "crassula-ovata", name: "Jade", latin_name: "Crassula ovata", family: "Crassulacées", description: "La plante de jade est une succulente aux feuilles ovales charnues vert foncé. Elle peut vivre des décennies et prend avec le temps l'aspect d'un petit arbre.", care_level: "facile", watering: "rare", watering_notes: "Laisser sécher complètement le substrat entre les arrosages. Très tolérante à la sécheresse.", light: "plein soleil", humidity: 30, temperature_min: 10, temperature_max: 35, soil: "Terreau pour succulentes et cactées", fertilizer: "Engrais pour succulentes une fois par mois en période de croissance", repotting: "Tous les 2-3 ans", origin: "Afrique du Sud, Mozambique", height_min: 20, height_max: 90, toxicity: "toxique", toxicity_details: "Légèrement toxique pour les chats et les chiens.", tags: ["succulente", "facile", "longévité", "intérieur"] },
  { slug: "geranium", name: "Géranium", latin_name: "Pelargonium zonale", family: "Géraniacées", description: "Le géranium est une plante incontournable des balcons et jardins. Ses fleurs colorées (rouge, rose, blanc) fleurissent du printemps aux premières gelées avec un entretien minimal.", care_level: "facile", watering: "modéré", watering_notes: "Arroser régulièrement mais sans excès. Laisser sécher légèrement le substrat entre deux arrosages.", light: "plein soleil", humidity: 40, temperature_min: 5, temperature_max: 30, soil: "Terreau pour géraniums ou terreau universel drainant", fertilizer: "Engrais pour plantes fleuries toutes les 2 semaines de mars à septembre", repotting: "Chaque printemps", origin: "Afrique du Sud", height_min: 20, height_max: 60, toxicity: "légèrement toxique", toxicity_details: "Légèrement toxique pour les animaux si ingéré en grande quantité.", tags: ["fleurs", "balcon", "extérieur", "coloré"] },
  { slug: "aglaonema", name: "Aglaonema", latin_name: "Aglaonema commutatum", family: "Aracées", description: "L'Aglaonema est une plante tropicale aux larges feuilles panachées de vert, argent, rouge ou rose. Très adaptable, elle supporte une faible luminosité et un entretien minimal.", care_level: "facile", watering: "modéré", watering_notes: "Arroser modérément, laisser sécher les 2 premiers cm entre les arrosages. Réduire en hiver.", light: "ombre", humidity: 50, temperature_min: 15, temperature_max: 30, soil: "Terreau universel bien drainant", fertilizer: "Engrais liquide toutes les 4 semaines de mars à septembre", repotting: "Tous les 2 ans au printemps", origin: "Asie tropicale", height_min: 30, height_max: 120, toxicity: "toxique", toxicity_details: "Toxique pour les animaux et irritant pour la peau.", tags: ["ombre", "feuillage coloré", "intérieur", "facile"] },
  { slug: "croton", name: "Croton", latin_name: "Codiaeum variegatum", family: "Euphorbiacées", description: "Le Croton est une plante tropicale aux feuilles flamboyantes aux couleurs spectaculaires : jaune, orange, rouge et vert. Un vrai tableau vivant pour les intérieurs ensoleillés.", care_level: "intermédiaire", watering: "régulier", watering_notes: "Arroser régulièrement, maintenir le substrat légèrement humide. Brumiser les feuilles.", light: "plein soleil", humidity: 60, temperature_min: 18, temperature_max: 30, soil: "Terreau universel riche et bien drainant", fertilizer: "Engrais liquide toutes les 2 semaines de mars à septembre", repotting: "Tous les 2 ans au printemps", origin: "Malaisie, Inde, Pacifique", height_min: 30, height_max: 100, toxicity: "toxique", toxicity_details: "La sève est irritante et toxique pour les humains et les animaux.", tags: ["feuillage coloré", "tropical", "intérieur", "coloré"] },
  { slug: "pilea-peperomioides", name: "Pilea", latin_name: "Pilea peperomioides", family: "Urticacées", description: "Le Pilea peperomioides, aussi appelé plante crêpe ou plante missionnaire, est reconnaissable à ses feuilles rondes portées par de longs pétioles. Très tendance et facile à multiplier.", care_level: "facile", watering: "modéré", watering_notes: "Arroser quand les 2 premiers cm de terre sont secs. Ne pas laisser dans l'eau stagnante.", light: "lumière indirecte", humidity: 50, temperature_min: 13, temperature_max: 30, soil: "Terreau universel léger avec un peu de perlite", fertilizer: "Engrais liquide une fois par mois de mars à septembre", repotting: "Tous les 2 ans ou quand les racines dépassent", origin: "Chine (Yunnan)", height_min: 15, height_max: 40, toxicity: "non toxique", toxicity_details: "Non toxique pour les humains et les animaux.", tags: ["tendance", "facile", "intérieur", "petite plante"] },
  { slug: "bambou-chanceux", name: "Bambou Chanceux", latin_name: "Dracaena sanderiana", family: "Asparagacées", description: "Le bambou chanceux n'est pas un vrai bambou mais un Dracaena aux tiges creuses. Symbole de bonheur et de prospérité dans la culture asiatique, il se cultive dans l'eau ou la terre.", care_level: "facile", watering: "modéré", watering_notes: "Peut pousser dans l'eau (changer tous les 15 jours) ou dans la terre légèrement humide.", light: "lumière indirecte", humidity: 50, temperature_min: 15, temperature_max: 30, soil: "Terreau universel ou culture hydroponique", fertilizer: "Engrais liquide dilué une fois par mois", repotting: "Tous les 2-3 ans si en terre", origin: "Cameroun, Afrique centrale", height_min: 20, height_max: 100, toxicity: "toxique", toxicity_details: "Toxique pour les chats et les chiens.", tags: ["porte-bonheur", "facile", "intérieur", "eau ou terre"] },
  { slug: "yucca", name: "Yucca", latin_name: "Yucca elephantipes", family: "Asparagacées", description: "Le Yucca est une plante originaire du Mexique aux longues feuilles rigides vert foncé. Très résistant et architectural, il s'adapte à de nombreux environnements.", care_level: "facile", watering: "rare", watering_notes: "Arroser peu, laisser sécher complètement entre deux arrosages. Très résistant à la sécheresse.", light: "plein soleil", humidity: 30, temperature_min: 7, temperature_max: 35, soil: "Terreau drainant avec sable ou perlite", fertilizer: "Engrais liquide une fois par mois en été", repotting: "Tous les 2-3 ans", origin: "Mexique, Amérique Centrale", height_min: 50, height_max: 400, toxicity: "toxique", toxicity_details: "Toxique pour les chats et les chiens. Les feuilles sont coupantes.", tags: ["architectural", "soleil", "résistant", "intérieur/extérieur"] },
];

async function fetchWikipediaImage(latinName: string, commonName: string): Promise<string | null> {
  const candidates = [latinName, commonName.toLowerCase(), latinName.split(" ")[0]];
  for (const name of candidates) {
    try {
      const title = name.replace(/ /g, "_");
      const res = await fetch(
        `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title)}`,
        { headers: { "User-Agent": "Bloomly/1.0" } }
      );
      if (!res.ok) continue;
      const data = await res.json();
      const image = data.thumbnail?.source ?? null;
      if (image) return image;
    } catch { continue; }
  }
  return null;
}

async function seed() {
  console.log(`🌱 Insertion de ${PLANTS.length} plantes...`);

  for (const plant of PLANTS) {
    // Vérifier si la plante existe déjà
    const { data: existing } = await supabase
      .from("plants")
      .select("id")
      .eq("slug", plant.slug)
      .single();

    if (existing) {
      console.log(`⏭️  ${plant.name} — déjà en base`);
      continue;
    }

    // Récupérer l'image Wikipedia
    const thumbnail = await fetchWikipediaImage(plant.latin_name, plant.name);
    await new Promise(r => setTimeout(r, 300));

    const { error } = await supabase.from("plants").insert({
      ...plant,
      thumbnail: thumbnail ?? "",
      images: [],
    });

    if (error) {
      console.error(`❌ ${plant.name} — ${error.message}`);
    } else {
      console.log(`✅ ${plant.name} ${thumbnail ? "📷" : "🖼️ (pas d'image)"}`);
    }
  }

  console.log("\n✨ Terminé !");
}

seed().catch(console.error);
